FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY tsconfig.base.json .
COPY apps/api apps/api
COPY apps/api/sql sql
RUN rm -rf apps/api/node_modules

RUN npm install --legacy-peer-deps && \
    npm run build --workspace @roboviz/api

ENV NODE_ENV=production
EXPOSE 4000

CMD ["node", "apps/api/dist/index.js"]


