FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json ./
COPY tsconfig.base.json .
COPY apps/api apps/api
COPY apps/web apps/web
RUN rm -rf apps/api/node_modules apps/web/node_modules

RUN npm install --legacy-peer-deps && \
    npm run build --workspace @roboviz/web

FROM nginx:alpine

COPY --from=builder /app/apps/web/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


